apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: cronjob-label-storage-nodes
  namespace: {{ .Values.odf.namespace }}
spec:
  schedule: {{ .Values.job.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ .Values.job.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.job.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          {{- include "odf.labelStorageNodes.podSpec" . | nindent 10 }}
