apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: job-label-storage-nodes
  namespace: {{ .Values.odf.namespace }}
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          {{- if .Values.storageSystem.inventory.useSpecificNodes }}
          {{- range .Values.storageSystem.inventory.nodes }}
          oc label node {{ . }} cluster.ocs.openshift.io/openshift-storage='' --overwrite
          {{- end }}
          {{- else }}
          oc label nodes -l node-role.kubernetes.io/worker= cluster.ocs.openshift.io/openshift-storage='' --overwrite
          {{- end }}
        name: label-storage-nodes
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: 400
