apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: job-label-storage-nodes
  namespace: {{ .Values.odf.namespace }}
spec:
  template:
    spec:
      {{- include "odf.labelStorageNodes.podSpec" . | nindent 6 }}
